package com.trionoputra.simplecrud;

import android.content.Intent;
import android.os.Parcelable;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;

import com.trionoputra.simplecrud.adapter.PeopleAdapter;
import com.trionoputra.simplecrud.object.People;

import java.util.List;

public class MainActivity extends AppCompatActivity {
    private RecyclerView recyclerView;
    private PeopleAdapter adapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        recyclerView = findViewById(R.id.recycler_view);
        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(mLayoutManager);
        recyclerView.setItemAnimator(new DefaultItemAnimator());


        adapter = new PeopleAdapter(this);
        recyclerView.setAdapter(adapter);

        adapter.setItemClickListener(new PeopleAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(People item) {
                Intent intent = new Intent(MainActivity.this,FormActivity.class);
                intent.putExtra("data",item.getId()); // id auto generated by sugar orm
                startActivity(intent);
            }
        });

        findViewById(R.id.buttonAdd).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(MainActivity.this,FormActivity.class);
                startActivity(intent);
            }
        });
    }

    public void getData()
    {
        List<People> data = People.listAll(People.class);
        adapter.set(data);

    }

    @Override
    protected void onResume() {
        super.onResume();

        getData();
    }
}
